### PR TITLE
Dictionary loading should not fail if .syn file doesn't exist

### PR DESCRIPTION
**Pull request by eschava**

### CODE REVIEW

**Comment by eschava** [comment]
@vvasuki Can I hope for a new release to the maven repository with this change?

**Comment by vvasuki** [comment]
I think I've done that just now, albeit with group id com.github.indic-dict. Doesn't show up at https://search.maven.org/search?q=g:com.github.indic-dict yet though.

**Comment by eschava** [comment]
I've found out that "However updates to search.maven.org can take up to two hours." but it is still absent there

**Comment by vvasuki** [comment]
Tried again. Should be out in two hours: "
Central sync is activated for com.github.indic-dict. After you successfully release, your component will be published to Central https://repo1.maven.org/maven2/, typically within 10 minutes, though updates to https://search.maven.org can take up to two hours."

**Comment by eschava** [comment]
Works now. Thanks a lot!

**Pull request merged**
